

extern double Elszakadasisebhat, Belsosav, G;
extern double  Talppontegybeolvadasitav;

extern double Ugrassebesseg1, Ugrassebesseg2;
extern double Ugroturelem;
extern double Vegenvaras;

extern double Drsugar, Drtang, Sr;

void initadatok( void );

extern double Magassag, Szelesseg;

extern vekt2 P_alap1, P_alap2, P_alap3, P_alap4, P_alap6;
extern double Fejsugar;

extern double Spritemaxsugar; // Targykereseshez!
extern double Ketmaxsugar; // Targykereseshez!

// MCGA kirajzolasos:

extern double Arany, Aranyx, Aranyy;


extern double Kord2x, Kord2y, Kord4x, Kord4y;

extern double Fekegyutthato;

