#include	"all.h"

void vonalki( int x1, int y1, int x2, int y2 ) {
	hiba( "vonalki Itt nem szabadna lennie!" );
	x1++;
	y1++;
	x2++;
	y2++;
}

// Ennek van egy mcga-s megfeleloje is mas paramokkal!:
void kiteljeskerek( int x, int y, int sugar, double alfa ) {
	hiba( "kiteljeskerek Itt nem szabadna lennie!" );
	x++;
	y++;
	sugar++;
	alfa++;
}

void bgitorol( void ) {
	hiba( "bgitorol Itt nem szabadna lennie!" );
}
