
void edithelp( void );

void menuhelp_exit( void );
void menuhelp_zoomout( void );
void menuhelp_save( void );
void menuhelp_save_as( void );
void menuhelp_open( void );
void menuhelp_new( void );
void menuhelp_play( void );
void menuhelp_zoom_fill( void );
void menuhelp_check( void );
void menuhelp_level_name( void );
// Toolok:
void menuhelp_move( void );
void menuhelp_zoom_in( void );
void menuhelp_create_vertex( void );
void menuhelp_delete_vertex( void );
void menuhelp_delete_polygon( void );
void menuhelp_create_food( void );
void menuhelp_create_killer( void );
void menuhelp_delete_object( void );
