#include	<stdio.h>
#include	<stdlib.h>
#include	<io.h>
#include	<dos.h>
#include	<conio.h>
#include	<mem.h>
#include	<string.h>
//#include	<alloc.h>
#include	<math.h>
#include	<time.h>
#include	<ctype.h>

#define WATCOM

#include	<i86.h>

#include	<graph.h>

#define VEGLEGES

//#define TEST

#include	"..\main.h"
#include	"..\pic8f.h"
#include	"..\pic8.h"
#include	"..\picmcga.h"
#include	"..\picl8ves.h"

#include	"..\abc8.h"

#include	"..\mouse.h"

#include	"..\rayback.h"

#include	"..\vekt2.h"
#include	"..\kor.h"
#include	"..\beallit.h"
#include	"..\leptet.h"
#include	"..\utkozes.h"
#include	"..\adatok.h"

#include	"..\recorder.h"

#include	"..\targy.h"

#include	"..\szakasz.h"
#include	"..\utkozes2.h"

#include	"..\magassag.h"
#include	"..\tegla.h"

#include	"..\egavga.h"

// Kozos:

#include	"..\kirajzol.h"

#include	"..\ratesz.h"

#include	"..\wav.h"
#include	"..\hang.h"
#include	"..\hanghigh.h"

#include	"..\bgi.h"

#include	"..\kiskep.h"
#include	"..\doboz.h"

#include	"..\valaszt.h"



#include	"..\leiro.h"
#include	"..\config.h"
#include	"..\state.h"
#include	"..\korny.h"


#include	"..\teljes.h"

#include	"..\jatekos.h"
#include	"..\mainmenu.h"
#include	"..\play.h"
#include	"..\skip.h"
#include	"..\besttime.h"

#include	"..\qopen.h"

#include	"..\kozos.h"
#include	"..\digit.h"

#include	"..\options.h"
#include	"..\crccheck.h"

#include	"..\newuj.h"

#include	"..\topol.h"
#include	"..\edituj.h"
#include	"..\dialog.h"
#include	"..\display.h"
#include	"..\edittool.h"
#include	"..\editmenu.h"
#include	"..\edittolt.h"

#include	"..\edithelp.h"
#include	"..\editplay.h"
#include	"..\ed_check.h"

#include	"..\m_dd.h"
#include	"..\m_k.h"
#include	"..\m_v.h"

#include	"..\d_nempub.h"

