#include    "all.h"

int editor( char* nev, palyaleiro* pleiro ) {
	nev++;
	pleiro++;
	hiba( "Ide nem johet (editor)!" );
	return  0;
}

void bgitorol( void ) {
	hiba( "Ide nem johet (bgitorol)!" );
}

void kirajzol640( double t, targytomb* pttt, double ugrasnagysag ) {
	hiba( "Ide nem johet (kirajzol640)!" );
	pttt++;
	t++;
	ugrasnagysag++;
}

// 640-be valt:
void setgraph( void ) {
}

void close640( void ) {
	hiba( "Ide nem johet (close640)!" );
}


