#include	<stdio.h>
#include	<stdlib.h>
#include	<io.h>
#include	<dos.h>
#include	<conio.h>
#include	<mem.h>
#include	<string.h>
#include	<alloc.h>
#include	<math.h>
#include	<time.h>

#include	<phapi.h>

#include	<graphics.h>

//#define VEGLEGES

#ifndef VEGLEGES
	#define TEST
#endif

//#include	"..\p-sos.h"

#include	"..\main.h"
#include	"..\picmcga.h"
//#include	"..\piclow.h"
#include	"..\pic8f.h"
#include	"..\pic8.h"
#include	"..\picl8ves.h"
#include	"..\imi_vesa.h"

#include	"..\abc8.h"

// EGAVGA-as verziohoz:

#include	"..\mouse.h"

#include	"..\rayback.h"

#include	"..\vekt2.h"
#include	"..\kor.h"
#include	"..\beallit.h"
#include	"..\leptet.h"
#include	"..\utkozes.h"
#include	"..\adatok.h"

#include	"..\recorder.h"

#include	"..\targy.h"

#include	"..\szakasz.h"
#include	"..\utkozes2.h"

#include	"..\editor.h"

#include	"..\magassag.h"
#include	"..\tegla.h"

#include	"..\egavga.h"

// Kozos:

#include	"..\graph.h"
#include	"..\kirajzol.h"
//#include	"..\hatter.h"


#include	"..\wav.h"
#include	"..\hang.h"
#include	"..\hanghigh.h"

#include	"..\bgi.h"

#include	"..\kiskep.h"
#include	"..\doboz.h"
#include	"..\ratesz.h"

#include	"..\valaszt.h"



#include	"..\leiro.h"
#include	"..\config.h"
#include	"..\state.h"
#include	"..\korny.h"


#include	"..\teljes.h"

#include	"..\jatekos.h"
#include	"..\mainmenu.h"
#include	"..\play.h"
#include	"..\skip.h"
#include	"..\besttime.h"

#include	"..\qopen.h"


#include	"..\kozos.h"

#include	"..\digit.h"

#include	"..\hordo.h"

#include	"..\options.h"
#include	"..\crccheck.h"

#include	"..\newuj.h"

#include	"..\topol.h"
#include	"..\edituj.h"
#include	"..\dialog.h"
#include	"..\display.h"

#include	"..\m_k.h"
#include	"..\m_v.h"
#include	"..\m_dd.h"



#include	"..\d_nempub.h"



